<?php
$EM_CONF[$_EXTKEY] = [
  'title' => 'Page module inline editing',
  'description' => 'Enables editing of content elements in the backend module without openening the content editing form (displays configurable form fields in preview, activates on click)',
  'category' => 'misc',
  'author' => 'Claus Due',
  'author_email' => 'claus@namelesscoder.net',
  'author_company' => '',
  'shy' => '',
  'dependencies' => '',
  'conflicts' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '1.0.5',
  'constraints' => [
    'depends' => [
      'php' => '5.6.0-7.0.99',
      'typo3' => '7.6.0-8.2.99',
    ],
    'conflicts' => [],
    'suggests' => [],
  ],
  'suggests' => [],
  '_md5_values_when_last_written' => '',
];
